.PHONY: clean All

All:
	@echo "==========Building project:[ variable_example - Debug ]=========="
	@cd "variable_example" && "$(MAKE)" -f  "variable_example.mk"
clean:
	@echo "==========Cleaning project:[ variable_example - Debug ]----------"
	@cd "variable_example" && "$(MAKE)" -f  "variable_example.mk" clean
