.PHONY: clean All

All:
	@echo "==========Building project:[ command_line - Debug ]=========="
	@cd "command_line" && "$(MAKE)" -f  "command_line.mk"
clean:
	@echo "==========Cleaning project:[ command_line - Debug ]----------"
	@cd "command_line" && "$(MAKE)" -f  "command_line.mk" clean
