.PHONY: clean All

All:
	@echo "==========Building project:[ Scanf_example - Debug ]=========="
	@cd "Scanf_example" && "$(MAKE)" -f  "Scanf_example.mk"
clean:
	@echo "==========Cleaning project:[ Scanf_example - Debug ]----------"
	@cd "Scanf_example" && "$(MAKE)" -f  "Scanf_example.mk" clean
